### ISSUE TITLE
AAD, I want to determine new potential features

### ISSUE THREAD

**Issue by karlogonzales** [karlogonzales/ministocks-390#1]
[Priority: 1]
[SP: 5]

AAD, I want to derive a list of potential features that can be added to the ministock widget. 

Potential ideas can be sourced from the ministocks issues list.
[https://github.com/niteshpatel/ministocks/issues](url)

List of potential features:
- Add cryptocurrency support
- Change portfolio shares to double (to support cryptocurrency)
- Resizing widget
- News of the stocks
- Switch between currency (CAN/US)
- Notifications for high/low
- Add ability to restore and backup data
- Reordering stocks in the widget
- Add scrollbar capability
- Full size widget
- Companion app

**Comment by Nick9500** [comment]
After discussion with TA Max on Jan 16, we have agreed to further investigate "Resize widget" as a primary first feature implementation for Release 1. If time permits, we also tentatively agreed to look into "Change font color option".
