### ISSUE TITLE
AAD, I would like to investigate how to implement scrollable widgets.

### ISSUE THREAD

**Issue by andypham29** [karlogonzales/ministocks-390#22]
Initial research indicates that widget does not support scrollable. This feature would be available only on a very limited number of devices. However there are many widgets available on all android devices that proves otherwise.  For example, google calendar's widget.

**Comment by Lattakia** [comment]
As was mentioned scrollview is not supported in app widget here is a link that shows the supported views in android widgets
https://developer.android.com/guide/topics/appwidgets/index.html#CreatingLayout
it seems that the only scrollable view supported is the listview which is incompatible with the structure of the text in the widget 
in the widget we use multiple horizontal layouts to fill widget rows, we also pass info from the xml file
if we are to use listview we will need to 1st pass the info from the java files and 2nd we need to restructure the presentation of the texts as listview may not have any children layouts

**Comment by iAlvisKhoo** [comment]
In the link you provided: [https://developer.android.com/guide/topics/appwidgets/index.html#CreatingLayout]

"**Android 3.0 introduces app widgets with collections. These kinds of App Widgets use the RemoteViewsService to display collections that are backed by remote data, such as from a content provider. The data provided by the RemoteViewsService is presented in the app widget using one of the following view types, which we’ll refer to as “collection views:”

ListView
A view that shows items in a vertically scrolling list. For an example, see the Gmail app widget.
GridView
A view that shows items in two-dimensional scrolling grid. For an example, see the Bookmarks app widget.**"

GridView is also one of the supported type with scrolling option.

I agree this task seem to be more complicated than expected and pushing it to our next spring would be ideal.
