### ISSUE TITLE
AAD, I want to investigate how to add stock datas without limits.

### ISSUE THREAD

**Issue by andypham29** [karlogonzales/ministocks-390#31]
# Description
Currently on the app, the implemented widget views allow a limited number of stocks that the user can add. This number depends on the size of the selected widget view.

The example below shows the number of stocked allowed for a 2x4 widget on the Nexus 5X.

![image](https://user-images.githubusercontent.com/25252836/36178988-afb9455a-10e8-11e8-986e-1af5ae1ac0f8.png)

# Investigate
Below are some aspects that can be investigated in order to solve this issue.
- [ ] Look into whether it is necessary to implement a different architecture of data display then the one currently implemented.
- [ ] Look into how to reuse the available code.
- [ ] Look into how widget layout and widget provider interacts.
- [ ] Look into internal storage for app development.

**Comment by Lattakia** [comment]
Some of the functions in the application were limiting the number of visible stocks so by modifying these functions we were able to increase the limit

**Comment by karlogonzales** [comment]
This issue is resolved with the new Scollable widget. Closing the issue.
