### ISSUE TITLE
AAD, I want to be able to connect the stock data to the new scollable view.

### ISSUE THREAD

**Issue by karlogonzales** [karlogonzales/ministocks-390#39]

**Comment by karlogonzales** [comment]
# Note
Our investigation shows that connecting the existing widget back end to the new widget would be very time consuming. 

# Suggestion
We should write our own controllers and services to feed our particular widget.

**Comment by andypham29** [comment]
Working on Issue #47 will help to figure out this issue.

**Comment by karlogonzales** [comment]
Branch #52 - Finished feature
