### ISSUE TITLE
AAD, I want to make the pre-existing unit tests passing

### ISSUE THREAD

**Issue by Nick9500** [karlogonzales/ministocks-390#4]
[Priority: 1]

As a developer, I want to make the pre-existing unit tests passing. 

As it stands, 7/22 unit tests are failing.

**Comment by karlogonzales** [comment]
# Description
I reran the tests on the master branch and I have gotten all the tests to pass without having to change code. It is possible that when we were running the tests before, we did not have the correct configuration or something in a previous pull request has rectified our problem.

# Configuration

![test-config](https://user-images.githubusercontent.com/16867596/35945525-80c6f102-0c2e-11e8-9fb3-bbfe33c21f42.JPG)

As you can see, I had all my tests pass using those Junit configuration settings.

# Suggestion
I think we should be able to close this issue #4

**Comment by karlogonzales** [comment]
# Notes
All pre-existing tests are passing on the master branch. Issue can be closed.
