### ISSUE TITLE
AAD, I want to test the UI using UI Automator

### ISSUE THREAD

**Issue by LamotheMax** [karlogonzales/ministocks-390#41]
Espresso will not work on a widget, please use UI Automator for your UI tests.

**Comment by hasan-ahmed** [comment]
I can get working on this. I already implemented a UI Automator test in the branch **resizeable-widget-test** that checks if the new widget sizes exist. I'll start adding tests for other fuctionality.

**Comment by karlogonzales** [comment]
That sounds good Ill have you
