### ISSUE TITLE
AAD, I want the UI for the functionalities of the custom menu for the scrollable widget

### ISSUE THREAD

**Issue by andypham29** [karlogonzales/ministocks-390#50]
## Description
UI for the functionalities of the custom menu.

Mark down when a task is done so we know what is left to be done.

## Task

- [ ] UI for Search
- [ ] UI for Add

**Comment by iAlvisKhoo** [comment]
Basic UI added.
![hii](https://user-images.githubusercontent.com/20878626/37498382-72b66142-2894-11e8-8344-667097768ce4.PNG)
