### ISSUE TITLE
AAU, I want to be able to refresh the content of the widget using a functioning refresh button

### ISSUE THREAD

**Issue by shayan-s** [karlogonzales/ministocks-390#58]

**Comment by hasan-ahmed** [comment]
# ACCEPTANCE TESTS

ID | Test Description | Acceptance Requirement | Critical | Test Result | Comment
-- | -- | -- | -- | -- | --
1 | Verify that the stock information can be refreshed from the new custom menu control. | The system shall refresh the stock information and the information shown will match what is shown on Google Finance for stocks and Crypto Compare for cryptocurrencies. | Yes | ACCEPTED:The information shown on refresh matches the google finance and cryptocompare information. |

**Comment by karlogonzales** [comment]
Feature was merged into master branch. This issue can be closed.
