### ISSUE TITLE
AAD, I want to implement static checking through SonarQube

### ISSUE THREAD

**Issue by karlogonzales** [karlogonzales/ministocks-390#68]

**Comment by hasan-ahmed** [comment]
![screen shot 2018-03-30 at 6 04 35 pm](https://user-images.githubusercontent.com/9097019/38157370-48bd6036-3454-11e8-8841-72057950cfa5.png)

I did an analysis using SonarQube locally and then when I integrate with Travis, I had to upgrade the android build tools to 26.0.2 and that break with the following errors even though I have added licenses to the travis.yml file:
![screen shot 2018-03-30 at 7 56 44 pm](https://user-images.githubusercontent.com/9097019/38157415-b44cbaf4-3454-11e8-8b14-0f2722073aee.png)

**Comment by karlogonzales** [comment]
# Note 
Sonar Cube script was not being called inside travis due to syntax error. Latest commit should fix the problem. It was committed directly into master. Issue can be closed

**Comment by hasan-ahmed** [comment]
SonarQube is working with travis!

![screen shot 2018-04-12 at 9 32 27 pm](https://user-images.githubusercontent.com/9097019/38712397-5f81419e-3e99-11e8-8c07-30b9d2a14758.png)
