### ISSUE TITLE
AAU, I want to remove a stock data from the list of stocks displayed on the scrollable widget.

### ISSUE THREAD

**Issue by andypham29** [karlogonzales/ministocks-390#71]

**Comment by andypham29** [comment]
The functionality is done. An item is being removed when click on the list of stock data. However there is a bug to it.

The filter feature on the remove functionality does not work properly. However, the stock item will still be removed from the stock list.

**List of stock set up by the Add activity:**
![image](https://user-images.githubusercontent.com/25252836/38716269-c8ae8bf4-3ead-11e8-9bf7-e240fcefde51.png)

**List of stock set up with the filtered input:**
![image](https://user-images.githubusercontent.com/25252836/38716280-d41a2368-3ead-11e8-9ea3-d82b6c3e4d65.png)

**Comment by hasan-ahmed** [comment]
# ACCEPANCE TEST
This story has been tested in test 2 (id=2) in the acceptance tests for issue #49
