### ISSUE TITLE
Bug: Widget displays an invalid list item if the symbol is invalid.

### ISSUE THREAD

**Issue by karlogonzales** [karlogonzales/ministocks-390#73]
Potential Fix: Create a conditional that would check the status of the response to determine if the list item should be displayed

**Comment by andypham29** [comment]
Patern matching has been added to search input. However it does not check for valid stock symbol.

**Comment by karlogonzales** [comment]
ListProvider now checks if the api response is invalid. 

https://github.com/karlogonzales/ministocks-390/commit/83e9e033c9df06bc7e95c5b9f9d3fb699b2c77cb
